workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Setup Folders
        script: mkdir -p assets # Manually creates the missing folder
      - name: Install dependencies
        script: npm install
      - name: Prebuild Android
        script: npx expo prebuild --platform android --no-install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - sapolang@gmail.com
