workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npx expo export:embed --platform android --dev false --output-dir dist
    artifacts:
      - dist/*.apk
    publishing:
      email:
        recipients:
          - sapolang@gmail.com # This will email you the link when done
